name 'can-mycanopy'
maintainer 'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'all_rights'
description 'Installs/Configures can-mycanopy'
long_description 'Installs/Configures can-mycanopy'
version '0.2.0'

depends 'apache2'
depends 'iptables'
depends 'jmh-db'
depends 'jmh-java'
depends 'jmh-server'
depends 'jmh-mule'
depends 'jmh-utilities'
depends 'openldap'
depends 'openssl'
depends 'pingfederate'
