name 'jmh-cq'
maintainer 'John Muir Health'
maintainer_email 'ebusiness@johnmuirhealth.com'
description 'Installs CQ AEM'
version '3.2.0'

depends 'apache2', '> 3.0.1'
depends 'jmh-bamboo'
depends 'jmh-epic'
depends 'jmh-fad'
depends 'jmh-java'
depends 'jmh-myjmh'
depends 'jmh-utilities'
depends 'jmh-webserver', '>= 0.3.0'
depends 'jmh-server'
depends 'logrotate'
depends 'systemd'
