Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "centos-6.5"
  c.vm.hostname = "apps02-centos-65"
  c.vm.network(:forwarded_port, {:guest=>8084, :host=>9084})
  c.vm.network(:forwarded_port, {:guest=>8088, :host=>9088})
  c.vm.network(:forwarded_port, {:guest=>8087, :host=>9087})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "2048"]
    p.customize ["modifyvm", :id, "--cpus", "4"]
  end
end
