name             'jmh-events'
maintainer       'John Muir Health'
maintainer_email 'ebusiness@johnmuirhealth.com'
license          'all_rights'
description      'Installs/Configures Event Manager'
long_description 'Installs/Configures Event Manager'
issues_url 'https://github.com/JohnMuirHealth/chef-repo'
source_url       'https://github.com/JohnMuirHealth/chef-repo'
version          '0.2.8'

depends 'jmh-apps'
depends 'jmh-crowd'
depends 'jmh-tomcat' , '>= 0.6.4'
depends 'jmh-db'
depends 'jmh-utilities'
depends 'openssl'
