name 'jmh-server'
maintainer       'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license          'all_rights'
description      'Installs/Configures jmh-server'
long_description 'Installs/Configures jmh-server for basic Firehost and JMH server config, networking, and users'
version '1.7.2'

depends 'chef-client'
depends 'chef_client_updater'
depends 'git'
depends 'iptables'
depends 'ntp'
depends 'postfix', '>= 4.0.0'
depends 'os-hardening'
depends 'ssh_known_hosts'
depends 'selinux'
depends 'sudo'
depends 'systemd'
depends 'timezone-ii'
depends 'users'
depends 'windows-hardening'
depends 'yum'
depends 'yum-epel'
