name             'jmh-rundeck'
maintainer       'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license          'All rights reserved'
description      'Installs/Configures jmh-rundeck'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url        'https://github.com/JohnMuirHealth'
source_url        'https://github.com/JohnMuirHealth'
version '0.7.3'

depends 'apache2'
depends 'iptables'
depends 'jmh-db'
depends 'jmh-events'
depends 'jmh-java'
depends 'jmh-server'
depends 'jmh-webserver'
depends 'jmh-utilities'
depends 'openssl'
# depends 'rundeck', '~> 4.2.0'
