
default['jmh_events']['report']['user'] = 'root'
default['jmh_events']['report']['group'] = 'root'
default['jmh_events']['report']['script_folder'] = '/tmp'
default['jmh_events']['report']['report_name'] = 'event_manager_registration_report'
default['jmh_events']['report']['report_folder'] =  '/tmp'
default['jmh_events']['report']['mysql_password'] = 'password'
default['jmh_events']['report']['archive_password'] = 'password'
default['jmh_events']['report']['rsa_file'] = '/home/jmhbackup/.ssh/id_rsa'
default['jmh_events']['report']['scp_user'] = 'jmhbackup'
default['jmh_events']['report']['scp_search'] = 'recipes:jmh-operations\:\:reports'
default['jmh_events']['report']['events_search'] = 'chef_environment:arprod AND recipes:jmh-events\:\:db'
default['jmh_events']['report']['scp_folder'] = '/var/www/html/reporting/event_manager'
default['jmh_events']['report']['archive_url'] = 'http://ebiz-tools.hsys.local/reporting/event_manager/'
default['jmh_events']['report']['email_address'] = 'melinda.moran@johnmuirhealth.com'