name             'jmh-billpay'
maintainer       'John Muir Health'
maintainer_email 'ebusiness@johnmuirhealth.com'
license          'all_rights'
description      'Installs/Configures jmh-billpay'
long_description 'Installs/Configures jmh-billpay'
version          '0.3.5'

depends 'jmh-tomcat'
depends 'jmh-utilities'
depends 'jmh-db'
depends 'openssl'
depends 'ssh_known_hosts'
