name 'jmh-apptapi'
maintainer 'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'all_rights'
description 'Installs/Configures jmh-apptapi'
long_description 'Installs/Configures jmh-apptapi'
version '0.4.2'

depends 'jmh-epic'
depends 'jmh-myjmh'
depends 'jmh-tomcat'
depends 'jmh-webserver'
depends 'jmh-utilities'
depends 'openssl'
