# to create a .robo_todo.yaml rubocop --auto-gen-config
LineLength:
  Max: 170
  
MethodLength:
  Max: 20
  
BlockNesting:
  Max: 3
  
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  
Style/SpecialGlobalVars:
  Enabled: false
  
Metrics/AbcSize:
  Max: 20
  
Style/FileName:
  Enabled: false