# NOTE - this file is no longer used for values...

default['jmh_epic']['java_properties_raw'] =
      ["# Defaults for All Environments",
       "mychart.auth.userid.header.name=USERID",
       "mychart.auth.token.cookie.name=AUTH_TOKEN",
       "mychart.proxy.cookie.name=MYJMHPROXYCOOKIE",
       "mychart.showfile.page=showfile.asp",
       "# Epic Services",
       "com.johnmuirhealth.isEpic2015=true",
      "epic.service.endpoint.wcf.patientAccess.basic2010=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/wcf/Epic.PatientAccess/PatientAccess.svc/basic_2010",
      "epic.service.endpoint.wcf.common.generatedServices.patient.basic=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/wcf/Epic.Common.GeneratedServices/Patient.svc/basic",
      "epic.service.endpoint.wcf.patientAccess.generatedServices.account.basic=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/wcf/Epic.PatientAccess.GeneratedServices/Account.svc/basic",
      "epic.service.endpoint.wcf.patientAccess.basic=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}//wcf/Epic.PatientAccess/PatientAccess.svc/basic",
      "epic.service.endpoint.wcf.common.generatedServices.patient.basic2012=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/wcf/Epic.Common.GeneratedServices/Patient.svc/basic_2012",
      "epic.service.endpoint.wcf.patientAccess.basic2011=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/wcf/Epic.PatientAccess/PatientAccess.svc/basic_2011",
      "epic.service.endpoint.mychart.patientAccess=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/httplistener.ashx",
      "epic.service.endpoint.interconnect.entitlements=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/httplistener.ashx",
      "epic.service.endpoint.patientAccessMobile.basic.2013=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/wcf/Epic.PatientAccessMobile.Services/PatientAccessMobile.svc/basic_2013",
      "epic.service.endpoint.patientAccessMobile.basic.2011=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/wcf/Epic.PatientAccessMobile.Services/PatientAccessMobile.svc/basic_2011",
      "epic.service.endpoint.patientAccessMobile.basic.2010=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}/wcf/Epic.PatientAccessMobile.Services/PatientAccessMobile.svc/basic",
      "mychart.host=${MYCHART.HOSTNAME}",
      "mychart.host.name=${MYCHART.HOSTNAME}",
      "mychart.tile.endpoint=443",
      "mychart.registry.key=${MYCHART.REGISTRY}",
      "mychart.access.check.url.path=/${MYCHART.CONTEXT}/accesscheck.asp",
      "mychart.base.path=/${MYCHART.CONTEXT}/",
      "mychart.cookie.domain=${WWW.SERVER_NAME}",
      "mychart.baseUrl=https://${MYCHART.HOSTNAME}",
      "mychart.insideAspBasePath=/${MYCHART.CONTEXT}/inside.asp?",
      "mychart.byeAspPath=/${MYCHART.CONTEXT}/bye.asp",
      "myjmh.client.datatile.url=https://${API.SERVER_NAME}/${MYCHART.CONTEXT}/",
      "mychart.datatile.url=https://${MYCHART.HOSTNAME}/${MYCHART.CONTEXT}/",
      "myjmh.datatile.url=https://${MYCHART.HOSTNAME}/${MYCHART.CONTEXT}/",
      "epic.baseUrl=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.CONTEXT}",
      "mychart.develop.token.allow=${MYCHART.DEVELOP_TOKEN}",
      "mychart.acordex.license=${MYCHART.ACORDEX}",
      "# Epic Secured Services ",
      "# To deprecate here to END",
      "com.johnmuirhealth.epic.interconnect.auth.username=${ZOCDOC.USERNAME}",
      "com.johnmuirhealth.epic.interconnect.auth.password=${ZOCDOC.PASSWORD}",
      "# END of deprecation",
      "com.johnmuirhealth.secure.endpoint=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.SECURE_CONTEXT}",
      "com.johnmuirhealth.epic.secure.endpoint=https://${INTERCONNECT.HOSTNAME}/${INTERCONNECT.SECURE_CONTEXT}",
      "# EPIC authentication",
      "com.johnmuirhealth.epic.interconnect.auth.clients=zocdoc,opensched,generic",
      "com.johnmuirhealth.epic.interconnect.auth.zocdoc.username=${ZOCDOC.USERNAME}",
      "com.johnmuirhealth.epic.interconnect.auth.zocdoc.password=${ZOCDOC.PASSWORD}",
      "com.johnmuirhealth.epic.interconnect.auth.zocdoc.allowedvisittypes=${ZOCDOC.VISITTYPE}",
      "com.johnmuirhealth.epic.interconnect.auth.opensched.username=${OPENSCHED.USERNAME}",
      "com.johnmuirhealth.epic.interconnect.auth.opensched.password=${OPENSCHED.PASSWORD}",
      "com.johnmuirhealth.epic.interconnect.auth.opensched.allowedvisittypes=${OPENSCHED.VISITTYPE}",
      "com.johnmuirhealth.epic.interconnect.auth.generic.username=${GENERIC.USERNAME}",
      "com.johnmuirhealth.epic.interconnect.auth.generic.password=${GENERIC.PASSWORD}",
      "com.johnmuirhealth.epic.interconnect.auth.generic.allowedvisittypes=${GENERIC.VISITTYPE}",
      "epic.service.clientId=${INTERCONNECT.CLIENTID}"]

default['jmh_epic']['additional_java_properties'] = []