Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.3"
  c.vm.hostname = "dispatcher-centos-73.vagrantup.com"
  c.vm.network(:forwarded_port, {:guest=>80, :host=>7080})
  c.vm.network(:forwarded_port, {:guest=>443, :host=>7443})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/melindam/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--cableconnected1", "on"]
    p.customize ["modifyvm", :id, "--memory", "2048"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
