name             'jmh-fad'
maintainer       'John Muir Health'
maintainer_email 'ebusiness@johnmuirhealth.com'
license          'all_rights'
description      'Installs/Configures jmh-webrequest'
long_description 'Installs/Configures jmh-webrequest'
version          '0.3.12'

depends 'jmh-db'
depends 'jmh-sched'
depends 'jmh-server'
depends 'jmh-tomcat'
depends 'jmh-utilities'
depends 'openssl'
