name 'jmh-db'
maintainer 'Scott Marshall, Melinda Moran'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'all_rights'
description 'Installs/Configures jmh-db'
long_description 'Installs/Configures jmh-db'
version '0.5.18'

depends 'database', '> 6.1.1'
depends 'jmh-encrypt'
depends 'jmh-server'
depends 'jmh-utilities'
depends 'logrotate'
depends 'mysql', '~> 8.5.0'
depends 'openssl'
