# to create a .robo_todo.yaml rubocop --auto-gen-config
LineLength:
  Max: 190
  
MethodLength:
  Max: 20
  
BlockNesting:
  Max: 3
  
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  
Style/SpecialGlobalVars:
  Enabled: false
  
Metrics/AbcSize:
  Max: 20
  
Style/FileName:
  Enabled: false