name 'jmh-pingfed'
maintainer 'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'all_rights'
description 'Installs/Configures PingFederate'
long_description 'Installs/Configures PingFederate'
version '0.6.0'

depends 'apache2'
depends 'iptables'
depends 'jmh-db'
depends 'jmh-java'
depends 'jmh-server'
depends 'jmh-epic'
depends 'jmh-utilities'
depends 'openldap'
depends 'openssl'
depends 'pingfederate', '~> 0.3.0'
