name 'jmh-webserver'
maintainer 'John Muir Health EBusiness'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'All rights reserved'
description 'Installs/Configures jmh-webserver'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url 'https://github.com/JohnMuirHealth'
source_url 'https://github.com/JohnMuirHealth'
version '0.5.44'

depends 'apache2', '>= 3.3.0'
depends 'iptables'
depends 'xml'
depends 'php'
depends 'jmh-encrypt'
depends 'jmh-epic'
depends 'jmh-pingfed'
depends 'jmh-server'
depends 'jmh-utilities'
depends 'logrotate', '>= 1.9.0'