name 'jmh-myjmh'
maintainer 'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'all_rights'
description 'Installs/Configures jmh-myjmh'
long_description 'Installs/Configures jmh-myjmh'
version '0.4.19'

depends 'jmh-apps'
depends 'jmh-db'
depends 'jmh-epic'
depends 'jmh-crowd'
depends 'jmh-encrypt'
depends 'jmh-nodejs'
depends 'jmh-tomcat'
depends 'jmh-pingfed'
depends 'jmh-utilities'
depends 'jmh-webserver'
depends 'jmh-server'
depends 'logrotate'
depends 'iptables'
depends 'systemd'
depends 'openssl'
