name 'jmh-infosec'
maintainer 'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'All Rights Reserved'
description 'Installs/Configures jmhinfo-ne'
long_description 'Installs/Configures jmhinfo-ne'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/JohnMuirHealth'
source_url 'https://github.com/JohnMuirHealth'

depends 'iis'
depends 'iis_urlrewrite'
depends 'jmh-server'
depends 'jmh-db'
depends 'openldap'
depends 'openssl'