name 'jmh-apps'
maintainer       'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license          'all_rights'
description      'Installs/Configures jmh-apps and databases'
long_description 'Installs/Configures JMH application and thier coorisponding mysql databases'
version '1.2.0'

depends 'jmh-db'
depends 'jmh-server'
depends 'jmh-tomcat'
depends 'jmh-crowd'
depends 'jmh-java'
depends 'jmh-webserver'
depends 'mysql'
depends 'openssl'
depends 'database'
depends 'subversion'
depends 'logrotate'
depends 'discovery'
depends 'ssh_known_hosts'
depends 'hostsfile'