Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "xianlin/rhel-7"
  c.vm.hostname = "base-xianlin-rhel-7.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-chef-repo-base-xianlin-rhel-7"
    p.customize ["modifyvm", :id, "--cableconnected1", "on"]
    p.customize ["modifyvm", :id, "--memory", "2048"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
