name 'jmh-broker'
maintainer 'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'all_rights'
description 'Installs/Configures jmh-broker'
long_description 'Installs/Configures jmh-broker'
version '0.4.1'

depends 'activemq'
depends 'iptables'
depends 'jmh-apps'
depends 'jmh-db'
depends 'jmh-encrypt'
depends 'jmh-epic'
depends 'jmh-java'
depends 'jmh-myjmh'
depends 'jmh-tomcat'
depends 'jmh-utilities'
depends 'openssl'
depends 'systemd'
