name             'jmh-docker'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures jmh-docker'
long_description 'Installs/Configures jmh-docker'
version          '0.1.0'

depends 'build-essential'
depends 'git'
depends 'docker'
depends 'gem_specific_install'
