name 'jmh-operations'
maintainer 'Scott Marshall'
maintainer_email 'scott.marshall@johnmuirhealth.com'
license 'all_rights'
description 'Installs/Configures jmh-operations'
long_description 'Installs/Configures jmh-operations'
version '1.2.16'

depends 'apache2'
depends 'git'
depends 'jmh-webserver'
depends 'jmh-cq'
depends 'jmh-crowd'
depends 'jmh-db'
depends 'jmh-encrypt'
depends 'jmh-epic'
depends 'jmh-idev'
depends 'jmh-java'
depends 'jmh-server'
depends 'jmh-utilities'
depends 'jmh-myjmh'
depends 'mysql'
depends 'subversion'
