name 'jmh-bamboo'
maintainer 'John Muir Health'
maintainer_email 'ebusiness@johnmuirhealth.com'
description 'Install and configure bamboo'

version '0.7.6'

depends 'apache2'
depends 'ark'
depends 'database'
depends 'git'
depends 'hostsfile'
depends 'iptables'
depends 'java'
depends 'jmh-ci'
depends 'jmh-db'
depends 'jmh-java'
depends 'jmh-myjmh'
depends 'jmh-server'
depends 'jmh-webserver'
depends 'jmh-nodejs'
depends 'jmh-mongodb'
depends 'mysql_connector'
depends 'openssl'
depends 'sonarqube'
depends 'systemd'
depends 'xmledit'
depends 'yum'
